### ISSUE TITLE
Custom headers are absent when served by Fastly.

### ISSUE THREAD

**Issue by kildapp** [fastly/next-compute-js#24]
Custom headers that are normally present in the response are absent when served by Fastly.

Get reproduction [here](https://github.com/kildapp/fastly-custom-header-bug)

**Comment by harmony7** [comment]
Thanks for reaching out!

Upon investigation we have identified the bug and made a correction: https://github.com/fastly/serve-vercel-build-output/commit/49fb2375d4f16ebfed88faff70bd32ad4b6b84eb

We've published a new version (`0.5.2`) of that library that includes the fix.

You can either:

* Delete the `next-compute-js` directory created by this tool and re-scaffold it with `npx @fastly/next-compute-js@alpha init`. This will always bring in the latest version of `@fastly/serve-vercel-build-output`.

or

* Go into the `next-compute-js` directory created by this tool and update `@fastly/serve-vercel-build-output`.

```
cd next-compute-js
npm install @fastly/serve-vercel-build-output@0.5.2
```

Run your application using `npm run fastly-serve` again and you should now see the headers from `next.config.js` and `middleware` being applied to your response.

I'm going to leave this open for a while longer, but please close it when you see it fixed. Thanks!

**Comment by mikil1** [comment]
Seems to be fixed now - thank you :-)

**Comment by kildapp** [comment]
Seems to be fixed now - thank you! :-)
